### ISSUE TITLE
Passing header as string doesn't work

### ISSUE THREAD

**Issue by philippfromme** [nikku/eslint-plugin-license-header#18]
### Describe the Bug

Passing the header as a string will result in the plugin treating it as a path to read from.

### Steps to Reproduce

Doesn't work:

```javascript
import licenseHeaderPlugin from 'eslint-plugin-license-header';

import apacheLicenseHeader from '../resources/apache-license-header.js'

export default [
  {
    plugins: {
      'license-header': licenseHeaderPlugin
    },
    rules: {
      'license-header/header': [2, apacheLicenseHeader]
    }
  }
]
```

Works:

```javascript
import licenseHeaderPlugin from 'eslint-plugin-license-header';

import apacheLicenseHeader from '../resources/apache-license-header.js'

export default [
  {
    plugins: {
      'license-header': licenseHeaderPlugin
    },
    rules: {
      'license-header/header': [2, apacheLicenseHeader.split('\n')]
    }
  }
]
```

### Expected Behavior

Passing header as string instead of array of strings works as to be expected from the name of the variable [`pathOrLicense`](https://github.com/nikku/eslint-plugin-license-header/blob/main/lib/rules/header.js#L79).

**Comment by nikku** [comment]
To my knowledge this works, in [according to the specification](https://github.com/nikku/eslint-plugin-license-header?tab=readme-ov-file#header-configuration). What are you missing?

**Comment by philippfromme** [comment]
I guess it works as expected then. I just stumbled over the fact I have to `.split('\n')` my header,
