### ISSUE TITLE
license-header.js content is missing

### ISSUE THREAD

**Issue by hansiemithun** [nikku/eslint-plugin-license-header#3]
How license-header.js should look like?

**Comment by nikku** [comment]
I do not get your question, sorry.

**Comment by hansiemithun** [comment]
is this supported in vue project ?

**Comment by nikku** [comment]
Still do not understand your question. 

What do you assume this library does? And what does not work?

**Comment by nikku** [comment]
Please spend a little bit more time to clearly explain your case. I otherwise cannot help you.

**Comment by hansiemithun** [comment]
I am extremely sorry to hear about it. Your plugin is great, I tried to incorporate in my Vue project, but that seems to be not working as per the expectations.

I used your simple example of having header.js to use as a template and it did generate the file header. But unfortunately for all the Vue files, it added as JS comment section and not seems to work. So, Is there any idea to support for Vue files or how to tweak to get this work for vue project?
