### ISSUE TITLE
Should handle trailing whitespace in license.js

### ISSUE THREAD

**Issue by srl295** [nikku/eslint-plugin-license-header#8]
__Describe the Bug__

Currently, trailing newlines are not allowed in the license.js. However,
many editors make it difficult to remove trailing newlines.

__Steps to Reproduce__

1. follow the user guide
2. introduce a newline at the end of the license.js file

__Expected Behavior__

Expected the license to work. However the license.js file and all source are considered invalid

__Environment__

n/a

**Comment by nikku** [comment]
Released with `v0.4.0`. Thanks for your contribution!

**Comment by srl295** [comment]
and thanks for this plugin.
